import shampoo1 from '../images/shop/demo/1.png';

const products = [
  {
    id: 1,
    category: 'Парфюм',
    name: 'Mewalo total black',
    descr: 'Парфюм от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 2,
    category: 'Кондиционеры',
    name: 'Mewalo total black',
    descr: 'Кондиционеры от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 3,
    category: 'Термозащита',
    name: 'Mewalo total black',
    descr: 'Термозащита от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 4,
    category: 'Помады',
    name: 'Mewalo total black',
    descr: 'Помады от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 5,
    category: 'Гель',
    name: 'Mewalo total black',
    descr: 'Гель от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 6,
    category: 'Мусс',
    name: 'Мусс total black',
    descr: 'Шампунь от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 7,
    category: 'Парфюм',
    name: 'Mewalo total black',
    descr: 'Парфюм от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 8,
    category: 'Кондиционеры',
    name: 'Mewalo total black',
    descr: 'Кондиционеры от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 9,
    category: 'Термозащита',
    name: 'Mewalo total black',
    descr: 'Термозащита от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 10,
    category: 'Помады',
    name: 'Mewalo total black',
    descr: 'Помады от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 11,
    category: 'Гель',
    name: 'Mewalo total black',
    descr: 'Гель от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 12,
    category: 'Мусс',
    name: 'Мусс total black',
    descr: 'Шампунь от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 13,
    category: 'Парфюм',
    name: 'Mewalo total black',
    descr: 'Парфюм от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 14,
    category: 'Кондиционеры',
    name: 'Mewalo total black',
    descr: 'Кондиционеры от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 15,
    category: 'Термозащита',
    name: 'Mewalo total black',
    descr: 'Термозащита от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 16,
    category: 'Помады',
    name: 'Mewalo total black',
    descr: 'Помады от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 17,
    category: 'Гель',
    name: 'Mewalo total black',
    descr: 'Гель от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
  {
    id: 18,
    category: 'Мусс',
    name: 'Мусс total black',
    descr: 'Шампунь от выпадения волос и бороды',
    direction: [
      'Для укладки волос',
    ],
    price: 2500,
    count: 1,
    img: shampoo1,
    href: '/product1',
  },
];

// for (let product of products) {
//   product.totalPrice = product.price * product.count;
// }

export default products;